Seed questions
vegaitsourcing/sos-zenski-centar pull request #38
Opened 2021-10-05 13:56 UTC by vlahovicv

-Reseni su kondicionali

-Izvucena je hardcoded url adresa na frontu i smestena u poseban fajl

-Docker fajl prepravljen za debug

2021-10-05 14:13 UTC, urosvegait requested changes

2021-10-05 14:13 UTC, urosvegait commented on sos-centar-api/Dockerfile
> +RUN dotnet build -c Debug -o /app
Docker moze biti debug ali samo na lokalu. Ne ide to na git

2021-10-05 14:13 UTC, urosvegait commented on sos-web/src/hooks/useNewEntryContext.js
> +      sendRequest(`http://localhost:48201/api/entries`, {
Zasto ovo? i ovde ide baseUrl

2021-10-05 14:13 UTC, urosvegait commented on sos-web/src/utils/apiUrl.js
> +export const baseUrl = "http://localhost:48201/api";
ovo treba u .env fajl

2021-10-05 14:27 UTC, vlahovicv commented on sos-web/src/hooks/useNewEntryContext.js
> +      sendRequest(`http://localhost:48201/api/entries`, {
Samo da proverim da li pratite pull :D
Salim se, ostalo ne izmenjeno, sredicemo

2021-10-05 14:27 UTC, vlahovicv commented on sos-web/src/utils/apiUrl.js
> +export const baseUrl = "http://localhost:48201/api";
Rekao mi jedan frontendas da stavim u utils, ali mogu premestiti i u env

2021-10-05 14:30 UTC, s-stankov commented on sos-web/src/utils/apiUrl.js
> +export const baseUrl = "http://localhost:48201/api";
stavi da utils cita iz .env fajla

2021-10-06 09:06 UTC, urosvegait approved these changes

2021-10-06 09:31 UTC, s-stankov approved these changes

2021-10-06 11:22 UTC, merged